# ===========================================================================
# DRY Docker Compose for Maybe
# ===========================================================================

x-rails-env: &rails_env
  RAILS_FORCE_SSL: "true"
  RAILS_ASSUME_SSL: "true"

x-common: &common
  restart: unless-stopped
  pull_policy: always
  networks:
    - homelab_network
  env_file:
    - .env.docker

x-cloudflared: &cloudflared
  image: cloudflare/cloudflared:latest
  <<: *common

services:
  web:
    image: ghcr.io/nikhilbadyal/maybe:latest
    container_name: maybe-web
    <<: *common
    expose:
      - "3000"
    volumes:
      - app-storage:/rails/storage
    environment:
      <<: *rails_env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/sessions/new" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  worker:
    image: ghcr.io/nikhilbadyal/maybe:latest
    container_name: maybe-worker
    <<: *common
    command: bundle exec sidekiq
    volumes:
      - app-storage:/rails/storage
    environment:
      <<: *rails_env
    healthcheck:
      test: ["CMD-SHELL", "bundle exec ruby -e \"require 'sidekiq'; require 'sidekiq/api'; ok = false; begin; pong = Sidekiq.redis { |c| c.ping } == 'PONG'; q = Sidekiq::Queue.new('default'); ok = pong && q.latency < 60; rescue => e; ok = false; end; exit(ok ? 0 : 1)\""]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

volumes:
  app-storage:

networks:
  homelab_network:
    external: true
