services:
  - type: web
    plan: free
    autoDeploy: false
    runtime: ruby
    name: maybe
    repo: https://github.com/nikhilbadyal/maybe.git
    branch: fixes
    healthCheckPath: /up
    buildCommand: "./bin/render-build.sh"

    # Uncomment if you are on a paid plan, and remove RUN_DB_MIGRATIONS_IN_BUILD_STEP from below
    # preDeployCommand: "bundle exec rails db:migrate"
    
    startCommand: "bundle exec rails server"
    envVars:
      - key: SELF_HOSTED
        value: true
      - key: HOSTING_PLATFORM
        value: render

      - key: WEB_CONCURRENCY
        value: 2
      - key: GOOD_JOB_EXECUTION_MODE
        value: async # Typically, `external` is used in prod, but this avoids another cron service and is generally fine for a self-hoster given low traffic

      - key: GITHUB_REPO_OWNER
        value: nikhilbadyal
      - key: GITHUB_REPO_NAME
        value: maybe
      - key: GITHUB_REPO_BRANCH
        value: fixes

      # Required to allow your self-hosted instance to be able to upgrade itself
      - key: UPGRADES_ENABLED
        value: true

      # If you upgrade your instance to a paid plan, you can set this to false (or remove it)
      # See note in `render-build.sh` script.
      - key: RUN_DB_MIGRATIONS_IN_BUILD_STEP
        value: true
