import_market_data:
  cron: "0 22 * * 1-5" # 5:00 PM EST / 6:00 PM EDT (NY time) Monday through Friday
  class: "ImportMarketDataJob"
  queue: "scheduled"
  description: "Imports market data daily at 5:00 PM EST (1 hour after market close)"
  args:
    mode: "full"
    clear_cache: false
  
clean_syncs:
  cron: "*/2 * * * *"  # every 2 minutes
  class: "SyncCleanerJob"
  queue: "scheduled"
  description: "Cleans up stale syncs"

run_security_health_checks:
  cron: "0 2 * * 1-5" # 2:00 AM EST / 3:00 AM EDT (NY time) Monday through Friday
  class: "SecurityHealthCheckJob"
  queue: "scheduled"
  description: "Runs security health checks to detect issues with security data"

sync_all_accounts:
  cron: "*/30 * * * *" # every 30 minutes
  class: "Accounts::SyncAllJob"
  queue: "scheduled"
  description: "Syncs all accounts for all families"
