name: Pull Request

on:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
